# Basic

In [1]:
import pandas as pd

In [2]:
data = {
    "name" : ["Riyad" , "Mahady" , "Zara"],
    "age" : [25,30,28],
    "city": ["Dhaka" ,"Cumila" , "Borisal"]
}

In [3]:
data

{'name': ['Riyad', 'Mahady', 'Zara'],
 'age': [25, 30, 28],
 'city': ['Dhaka', 'Cumila', 'Borisal']}

# Dataframe

In [5]:
df = pd.DataFrame(data)
print(df)

     name  age     city
0   Riyad   25    Dhaka
1  Mahady   30   Cumila
2    Zara   28  Borisal

# Read File

In [25]:
df = pd.read_csv('/content/titanic.csv')

# Index_based and label based selection

In [26]:
#iloc index based
print(df.iloc[0])
print(df.iloc[0:3])
print(df.iloc[0:3,1])

PassengerId                 892
Survived                      0
Pclass                        3
Name           Kelly, Mr. James
Sex                        male
Age                        34.5
SibSp                         0
Parch                         0
Ticket                   330911
Fare                     7.8292
Cabin                       NaN
Embarked                      Q
Name: 0, dtype: object
   PassengerId  Survived  Pclass                              Name     Sex  \
0          892         0       3                  Kelly, Mr. James    male
1          893         1       3  Wilkes, Mrs. James (Ellen Needs)  female
2          894         0       2         Myles, Mr. Thomas Francis    male

    Age  SibSp  Parch  Ticket    Fare Cabin Embarked
0  34.5      0      0  330911  7.8292   NaN        Q
1  47.0      1      0  363272  7.0000   NaN        S
2  62.0      0      0  240276  9.6875   NaN        Q
0    0
1    1
2    0
Name: Survived, dtype: int64

In [27]:
#iloc label based
print(df.loc[0])
print(df.loc[0:3])
print(df.loc[0:3])

PassengerId                 892
Survived                      0
Pclass                        3
Name           Kelly, Mr. James
Sex                        male
Age                        34.5
SibSp                         0
Parch                         0
Ticket                   330911
Fare                     7.8292
Cabin                       NaN
Embarked                      Q
Name: 0, dtype: object
   PassengerId  Survived  Pclass                              Name     Sex  \
0          892         0       3                  Kelly, Mr. James    male
1          893         1       3  Wilkes, Mrs. James (Ellen Needs)  female
2          894         0       2         Myles, Mr. Thomas Francis    male
3          895         0       3                  Wirz, Mr. Albert    male

    Age  SibSp  Parch  Ticket    Fare Cabin Embarked
0  34.5      0      0  330911  7.8292   NaN        Q
1  47.0      1      0  363272  7.0000   NaN        S
2  62.0      0      0  240276  9.6875   NaN        Q
3  27.0      0      0  315154  8.6625   NaN        S
   PassengerId  Survived  Pclass                              Name     Sex  \
0          892         0       3                  Kelly, Mr. James    male
1          893         1       3  Wilkes, Mrs. James (Ellen Needs)  female
2          894         0       2         Myles, Mr. Thomas Francis    male
3          895         0       3                  Wirz, Mr. Albert    male

    Age  SibSp  Parch  Ticket    Fare Cabin Embarked
0  34.5      0      0  330911  7.8292   NaN        Q
1  47.0      1      0  363272  7.0000   NaN        S
2  62.0      0      0  240276  9.6875   NaN        Q
3  27.0      0      0  315154  8.6625   NaN        S

In [29]:
print(df.loc[0,"Name"])
print(df.loc[:, "Age"])
print(df.loc[df.Age>25])

Kelly, Mr. James
0      34.5
1      47.0
2      62.0
3      27.0
4      22.0
       ...
413     NaN
414    39.0
415    38.5
416     NaN
417     NaN
Name: Age, Length: 418, dtype: float64
     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
6            898         1       3
..           ...       ...     ...
407         1299         0       1
411         1303         1       1
412         1304         1       3
414         1306         1       1
415         1307         0       3

                                                Name     Sex   Age  SibSp  \
0                                   Kelly, Mr. James    male  34.5      0
1                   Wilkes, Mrs. James (Ellen Needs)  female  47.0      1
2                          Myles, Mr. Thomas Francis    male  62.0      0
3                                   Wirz, Mr. Albert    male  27.0      0
6                               Connolly, Miss. Kate  female  30.0      0
..                                               ...     ...   ...    ...
407                       Widener, Mr. George Dunton    male  50.0      1
411  Minahan, Mrs. William Edward (Lillian E Thorpe)  female  37.0      1
412                   Henriksson, Miss. Jenny Lovisa  female  28.0      0
414                     Oliva y Ocana, Dona. Fermina  female  39.0      0
415                     Saether, Mr. Simon Sivertsen    male  38.5      0

     Parch              Ticket      Fare Cabin Embarked
0        0              330911    7.8292   NaN        Q
1        0              363272    7.0000   NaN        S
2        0              240276    9.6875   NaN        Q
3        0              315154    8.6625   NaN        S
6        0              330972    7.6292   NaN        Q
..     ...                 ...       ...   ...      ...
407      1              113503  211.5000   C80        C
411      0               19928   90.0000   C78        Q
412      0              347086    7.7750   NaN        S
414      0            PC 17758  108.9000  C105        C
415      0  SOTON/O.Q. 3101262    7.2500   NaN        S

[190 rows x 12 columns]

# Basic Operation

In [30]:
print('DataFrame Shape:', df.shape)
print('\nDataFrame Columns:', df.columns.tolist())
print('\nDataFrame Info:')
df.info()
print('\nDataFrame Description:')
display(df.describe())

DataFrame Shape: (418, 12)

DataFrame Columns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

DataFrame Description:

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

# Missing value

In [34]:
df.isnull().sum()

city      0
salary    0
dtype: int64

First, let's confirm the missing values in the `titanic` dataset.

In [35]:
print('Missing values before handling:')
df.isnull().sum()

Missing values before handling:

city      0
salary    0
dtype: int64

In [39]:
df = pd.read_csv('/content/titanic.csv')

# Fill missing 'Age' values with the mean age
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Fill missing 'Fare' values with the mean fare
df['Fare'].fillna(df['Fare'].mean(), inplace=True)

# Drop the 'Cabin' column due to many missing values
df.drop('Cabin', axis=1, inplace=True)

print('\nMissing values after handling:')
display(df.isnull().sum())

Missing values after handling:

/tmp/ipykernel_7116/3317546767.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipykernel_7116/3317546767.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fare'].fillna(df['Fare'].mean(), inplace=True)

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [40]:
display(df.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S

Now, let's handle the missing values:

*   **Age**: Fill missing values with the mean age.
*   **Fare**: Fill missing values with the mean fare.
*   **Cabin**: This column has a large number of missing values, so we'll drop it.

In [38]:
df = pd.read_csv('/content/titanic.csv')

# Fill missing 'Age' values with the mean age
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Fill missing 'Fare' values with the mean fare
df['Fare'].fillna(df['Fare'].mean(), inplace=True)

# Drop the 'Cabin' column due to many missing values
df.drop('Cabin', axis=1, inplace=True)

print('\nMissing values after handling:')
display(df.isnull().sum())

Missing values after handling:

/tmp/ipykernel_7116/3317546767.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipykernel_7116/3317546767.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fare'].fillna(df['Fare'].mean(), inplace=True)

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

Here's a preview of the DataFrame after handling missing values:

In [37]:
display(df.head())

      city  salary
0    Dhaka    1000
1    Dhaka    3000
2  Cumilla     600
3  Cumilla    4000

# Group by

In [31]:
data = {
    "city":["Dhaka" , "Dhaka" , "Cumilla" , "Cumilla"],
    "salary": [1000,3000,600,4000]
    }

df = pd.DataFrame(data)

grouped = df.groupby("city")["salary"].sum()
print(grouped)

city
Cumilla    4600
Dhaka      4000
Name: salary, dtype: int64